# Generated by Django 4.1.3 on 2024-01-13 16:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('type', models.CharField(max_length=14)),
                ('varietal', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('consumed', models.BinaryField()),
                ('date_consumed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
