# Generated by Django 4.1.3 on 2024-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wines',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
